#File di configurazione, inserisci intervallo in secondi su read_interval
db_address: ....
db_port: .....
db_user: .....
db_pass: .....
db_name: .....
db_table: meteo
read_interval: 60
sensor_endpoint: ......
